export const SUBJ_DETAILS_DUMMY_DATA = [
  {
    id: '11',
    departmentId: '1',
    subject: 'Filipino',
    subjectDescription: 'Description',
    offeredTo: 'Grade 7',
  },
  {
    id: '12',
    departmentId: '1',
    subject: 'English',
    subjectDescription: 'Description',
    offeredTo: 'Grade 7',
  },
  {
    id: '13',
    departmentId: '1',
    subject: 'Mathematics',
    subjectDescription: 'Description',
    offeredTo: 'Grade 7',
  },
  {
    id: '14',
    departmentId: '1',
    subject: 'Science',
    subjectDescription: 'Description',
    offeredTo: 'Grade 7',
  },
  {
    id: '15',
    departmentId: '1',
    subject: 'Araling Panlipunan (AP)',
    subjectDescription: 'Description',
    offeredTo: 'Grade 7',
  },
  {
    id: '16',
    departmentId: '1',
    subject: 'Edukasyon sa Pagpapakatao (ESP)',
    subjectDescription: 'Description',
    offeredTo: 'Grade 7',
  },
  {
    id: '17',
    departmentId: '1',
    subject: '	Technology and Livelihood Education (TLE)',
    subjectDescription: 'Description',
    offeredTo: 'Grade 7',
  },
  {
    id: '18',
    departmentId: '1',
    subject: 'MAPEH',
    subjectDescription: 'Description',
    offeredTo: 'Grade 7',
  },
  {
    id: '19',
    departmentId: '1',
    subject: 'Music',
    subjectDescription: 'Description',
    offeredTo: 'Grade 7',
  },
  {
    id: '20',
    departmentId: '1',
    subject: 'Arts',
    subjectDescription: 'Description',
    offeredTo: 'Grade 7',
  },
];
